# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mlFZQ-640v70OWctJYiaXMwLkf5bN6qP
"""

from matplotlib import pyplot as plt
import numpy as np
import math 

x=np.arange(-2*np.pi,2*np.pi,0.01)
plt. plot(x,np.sin(x))
plt.plot(x,np.sin(x)*np.cos(x)*2)
plt.plot(x,np.sin(x)/math.sqrt(2)+np.cos(x)/math.sqrt(2))
plt.show()